# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/Yoo.Trainees.ShipWars.Api.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/Yoo.Trainees.ShipWars.Api.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/Yoo.Trainees.ShipWars.Api.Test.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/Yoo.Trainees.ShipWars.Api.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Yoo.Trainees.WarShip/Frontend'
    ArtifactName: 'frontend'